# Generated by Django 3.2.5 on 2021-09-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AssetsApp', '0001_initial'),
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('AssetsApp.assets',),
        ),
        migrations.CreateModel(
            name='TransactionsDB',
            fields=[
                ('transaction_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('datetime_stamp', models.DateTimeField()),
                ('type', models.CharField(max_length=20)),
                ('from_account', models.CharField(max_length=30, null=True)),
                ('to_account', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('from_amount', models.PositiveBigIntegerField(null=True)),
                ('from_currency', models.CharField(max_length=5, null=True)),
                ('to_amount', models.PositiveBigIntegerField(null=True)),
                ('to_currency', models.CharField(max_length=5, null=True)),
                ('fees', models.CharField(max_length=30, null=True)),
                ('exchange_rate', models.PositiveBigIntegerField(null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachments', models.FilePathField(allow_folders=True, null=True)),
                ('user', models.CharField(max_length=40, null=True)),
                ('budget_id', models.CharField(max_length=40, null=True)),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.enterprises')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('flow_type', models.CharField(max_length=40)),
                ('parent_id', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_sub_category', models.BooleanField()),
                ('datetime_added', models.DateTimeField()),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.enterprises')),
            ],
        ),
    ]
