# Generated by Django 3.2.5 on 2021-09-07 20:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AuthenticationApp', '0001_initial'),
        ('FinanceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsCategories',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('datetime_added', models.DateTimeField(default=datetime.datetime(2021, 9, 7, 20, 16, 38, 954104))),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.enterprises')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='TransactionCategories',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('asset_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('status', models.CharField(help_text='0 Is Inservice, 1 is Inactive and 3 Under Maintaince', max_length=20)),
                ('currency', models.CharField(max_length=5, null=True)),
                ('datetime_added', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceApp.accountscategories')),
                ('enterprise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.enterprises')),
            ],
        ),
    ]
