# Generated by Django 3.2.5 on 2021-09-07 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0002_auto_20210907_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountscategories',
            name='datetime_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 20, 46, 10, 148652)),
        ),
        migrations.AlterModelTable(
            name='accountscategories',
            table='AccountsCategories',
        ),
    ]
