# Generated by Django 3.2.5 on 2021-09-08 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0003_auto_20210907_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountscategories',
            name='datetime_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 1, 7, 9, 726036)),
        ),
        migrations.AlterModelTable(
            name='accountscategories',
            table='FinanceApp_AccountsCategories',
        ),
    ]
