# Generated by Django 3.2.5 on 2021-09-08 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
        ('FinanceApp', '0004_auto_20210908_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionCategories',
            new_name='TransactionsCategories',
        ),
        migrations.AlterField(
            model_name='accountscategories',
            name='datetime_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 1, 37, 54, 78262)),
        ),
    ]
