# Generated by Django 3.2.5 on 2021-09-08 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0005_auto_20210908_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='asset_id',
            new_name='account_id',
        ),
        migrations.AddField(
            model_name='accounts',
            name='class_term',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountscategories',
            name='datetime_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 1, 47, 17, 399656)),
        ),
        migrations.AlterModelTable(
            name='transactionscategories',
            table='FinanceApp_TransactionsCategories',
        ),
    ]
