# Generated by Django 3.2.5 on 2021-09-08 02:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0007_auto_20210908_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountscategories',
            name='datetime_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 2, 36, 18, 608741)),
        ),
        migrations.AlterField(
            model_name='transactionscategories',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinanceApp.transactionscategories'),
        ),
        migrations.AlterModelTable(
            name='transactionsdb',
            table='FinanceApp_Transactions',
        ),
    ]
