# Generated by Django 3.2.5 on 2021-09-08 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FinanceApp', '0008_auto_20210908_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountscategories',
            name='datetime_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transactionsdb',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='FinanceApp.transactionscategories'),
        ),
        migrations.AlterField(
            model_name='transactionsdb',
            name='fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FinanceApp.transactionsdb'),
        ),
        migrations.AlterField(
            model_name='transactionsdb',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='FinanceApp.accounts'),
        ),
        migrations.AlterField(
            model_name='transactionsdb',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='FinanceApp.transactionscategories'),
        ),
        migrations.AlterField(
            model_name='transactionsdb',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='FinanceApp.accounts'),
        ),
        migrations.AlterField(
            model_name='transactionsdb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.user'),
        ),
    ]
