# Generated by Django 3.2.5 on 2021-09-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0009_auto_20210908_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionscategories',
            name='flow_type',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionsdb',
            name='type',
            field=models.SmallIntegerField(),
        ),
    ]
