# Generated by Django 3.2.5 on 2021-09-30 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FinanceApp', '0010_auto_20210908_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionscategories',
            name='user_id',
            field=models.ForeignKey(default='hh', on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.user'),
            preserve_default=False,
        ),
    ]
