# Generated by Django 3.2.5 on 2021-09-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceApp', '0011_transactionscategories_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionscategories',
            name='comment',
        ),
        migrations.AddField(
            model_name='transactionscategories',
            name='name',
            field=models.CharField(default='h', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionscategories',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
