# Generated by Django 3.2.5 on 2021-09-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AssetsApp', '0001_initial'),
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetscategories',
            name='enterprise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.enterprises'),
        ),
        migrations.AddField(
            model_name='assets',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetsApp.assetscategories'),
        ),
        migrations.AddField(
            model_name='assets',
            name='enterprise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.enterprises'),
        ),
        migrations.AddField(
            model_name='assets',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='AssetsApp.assetscategories'),
        ),
    ]
