# Generated by Django 3.2.5 on 2021-09-06 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetsApp', '0003_auto_20210906_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetscategories',
            name='user',
        ),
        migrations.AlterField(
            model_name='assetscategories',
            name='datetime_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 16, 12, 25, 396718)),
        ),
    ]
