# Generated by Django 3.2.5 on 2021-09-07 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetsApp', '0006_auto_20210907_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetscategories',
            name='datetime_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 20, 16, 38, 820104)),
        ),
    ]
