# Generated by Django 3.2.5 on 2021-09-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetsApp', '0014_alter_assetscategories_datetime_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetscategories',
            name='datetime_added',
            field=models.DateTimeField(),
        ),
    ]
